### ISSUE TITLE
To-do

### ISSUE THREAD

**Issue by pastko** [codestates/BTC1stProject-08#2]
### 코인
- [x] Avalanche 코인
### 프론트엔드
- [x] Vue.js 기반 웹페이지 

### 백엔드
- [x] Node.js 기반 백엔드

### DB
- [x] MySQL 

### 지갑
- [x] 지갑생성 : 니모닉
- [x] 잔고조회
- [x] 코인 입급&송금
- [x] Account 추가

### 익스플로러 
- [ ] 블록정보 검색 / 최근( ex : 1 hour ) 블록정보 조회  : 블록id
- [ ] 트랜젝션 검색 / 최근( ex : 1 hour ) 트랜젝션 조회  : 트랜젝션 Number ( HEX )
- [ ] 노드 정보

- 참조
아발란체 익스 (https://explorer.avax-test.network/)
이더 스켄 (https://etherscan.io/)
아발란체 지갑 (https://wallet.avax.network/access)
Docs (https://docs.avax.network/build/tools/avalanchejs)

## Advanced 
- [ ] 크롬 확장 프로그램 지원
- [ ] 메인넷 / 테스트넷
